### ISSUE TITLE
Some thoughts

### ISSUE THREAD

**Issue by thyrlian** [vudin/clocktube#1]
* Styling of README is ugly :P
* Need a baby pic in the README :)
* If it's a fresh start, why not Kotlin?

**Comment by vudin** [comment]
Thanks! I just restyled the README. I may also add a generic baby pic later, and some screenshots from the app.

> Why not Kotlin?

 Because I didn't have enough time to learn + setup my environment for it. Definitely on my roadmap.

**Comment by thyrlian** [comment]
Much better now 👍 

Come on dude, now Kotlin or never :)
